# -*- coding: utf-8 -*-
"""Student_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpSfo3siTz8SDdOhwLDy7xtOV7YwnOOe
"""

# This represents the data in 'schema'
students = [
    {"name": "Alice", "score": 85},
    {"name": "Bob", "score": 92},
    {"name": "Charlie", "score": 45},
    {"name": "David", "score": 78},
    {"name": "Eve", "score": 48}
]

print(f"Loaded {len(students)} student records.")

def calculate_stats(student_list):
    if not student_list:
        return None

    scores = [s['score'] for s in student_list]

    # Basic Statistics
    avg_score = sum(scores) / len(scores)
    highest = max(student_list, key=lambda x: x['score'])
    lowest = min(student_list, key=lambda x: x['score'])

    # Pass/Fail counts (Pass >= 50)
    pass_count = len([s for s in scores if s >= 50])
    fail_count = len([s for s in scores if s < 50])

    stats = {
        'average': avg_score,
        'highest': highest,
        'lowest': lowest,
        'pass_count': pass_count,
        'fail_count': fail_count
    }

    return stats


results = calculate_stats(students)
print(results)

import matplotlib.pyplot as plt

def plot_pass_fail(stats):
    labels = ['Pass', 'Fail']
    counts = [stats['pass_count'], stats['fail_count']]

    plt.bar(labels, counts, color=['green', 'red'])
    plt.xlabel('Status')
    plt.ylabel('Number of Students')
    plt.title('Student Performance: Pass vs Fail')
    plt.show()

# Generate the chart
plot_pass_fail(results)